### ISSUE TITLE
Mise en place d'un flux de données pour reverser les décisions dans la BDD SDER

### ISSUE THREAD

**Issue by BenoitSerrano** [Cour-de-cassation/sder#4]
## Schéma de la table `decisions` de la base SDER
decisions : `text`, `is_loaded_in_label`, `pseudonymised_text`

## Flux de donnée
- lancement quotidien du script `importNewDocumentsFromSder` depuis Label
  - récupère les documents dont le champ `is_loaded_in_label` est `false`
  - insertion des documents dans la BDD *label*
  - pour tous les documents pour lesquels l'insertion en base de données sur Label s'est bien passée, update du champ `is_loaded_in_label` de la base *sder*
- lancement du script `annotateDocumentsWithoutAnnotationsWithNlp`
  - récupération des documents dans la BDD label qui n'ont pas été traités (ni par le moteur NLP, ni par un agent annotateur)
  - appels _successifs_ de l'API du moteur NLP pour chaque document récupéré
  - stockage dans la BDD *label* du traitement effectué par le moteur NLP pour chaque document

- lancement hebdomadaire du script `storeTreatedDocumentsIntoSder`
  - récupération des documents dans la BDD *sder* dont le champ `is_loaded_in_label` est  `true` et `pseudonymised_text` est non vide
  - récupération dans la BDD *label* des documents et traitements correspondant à ceux récupérés au point précédent
  - pseudonymisation des documents de la BDD *label* à partir des traitements
  - stockage dans la BDD *sder* du texte pseudonymisé pour chaque document

## Route API requise
- GET `/unloaded-documents` : récupération des documents dont le champ is_loaded_in_label est false
- PATCH `/update-documents-loaded-status`, args: documentIds : update du champ `is_loaded_in_label`
- PATCH `/update-document-pseudonymised-text`, args : {documentId, pseudonymised_text} : update du champ `pseudonymised_text`
- GET `/untreated-documents` : récupération des documents dont le champ `is_loaded_in_label` est  `true` et `pseudonymised_text` est non vide

**Comment by fondation451** [comment]
## The decisions collection of the SDER DB

Fields used by LABEL: `pseudoText`.

New fields needed: `isLoadedInLabel` and `labelTreatments`

## Data Flow
- run each day `importNewDocumentsFromSder` script from LABEL
  - fetch the decisions that have `isLoadedInLabel` to false and no `pseudoText`
  - insertion in the DB *label*
  - update the field  `isLoadedInLabel` to true in the SDER DB


- run on a weekly basis the script `exportTreatedDocumentsIntoSder`
  - fetch in LABEL DB all the document ready to be exported
  - verification that these documents can be exported
  - completion of the field `pseudoText`, `isLoadedInLabel` and `labelTreatments` in SDER DB

## API of SDER
- GET `/label/decisions-to-pseudonymise` : fetch the decisions with  `isLoadedInLabel` to false and no `pseudoText`
- PATCH `/label/update-decision-pseudonymisation`, args : {documentId, pseudoText} : update `pseudoText` field, the status, and the treatments

**Comment by fondation451** [comment]
Done
