### ISSUE TITLE
Metadonnées jurinet et jurica

### ISSUE THREAD

**Issue by mauryaland** [Cour-de-cassation/sder#40]
Pour l'instant les metadonnées sont requêtables via l'api de pseudonymisation et les endpoints [meta-jurinet](https://github.com/Cour-de-cassation/nlp-pseudonymisation-api/blob/f1fd166445c0e2b14ed8400e4747755a5e29eb0b/app.py#L153) et  [meta-jurica](https://github.com/Cour-de-cassation/nlp-pseudonymisation-api/blob/f1fd166445c0e2b14ed8400e4747755a5e29eb0b/app.py#L219). Ces endpoints vont chercher directement les metadonnées dans les BDD Oracle et les uniformisent en CSV.

Le problème est que la route théorique des métadonnées dans le processus de pseudonymisation est inutilement compliquée : 
1) la base SDER requête les endpoints meta-jurinet et meta-jurica via l'ID Oracle du document dans l'API de pseudonymisation qui va taper les BDD Oracle et renvoyer les metadonnées uniformisées dans mongodb
2) LABEL récupère les métadonnées uniformisées dans la base SDER en même temps que la décision pour l'envoyer au endpoint ner de l'API de pseudonymisation

Pour éviter que l'API de pseudonymisation requête Oracle et reste bien isolée, nous avons convenu avec Sébastien qu'il récupérerait directement les métadonnées en format brute (sachant que c'était déjà le cas pour Jurica car il s'agit d'une colonne de la table principale *JDEC_COLL_PARTIES* de la table *JDEC_DECISION*, pour Jurinet il s'agit d'une vue *VIEW_PARTIE*).

Je propose que la base SDER envoie directement les métadonnées brutes et la source (jurinet ou jurica) aux endpoints meta-jurica/jurinet (à adapter entre temps) qui vont uniformiser celles-ci pour qu'elles soient stockées dans mongo, LABEL n'aura plus qu'à les récupérer pour les envoyer au endpoint ner avec le texte de la décision => cela évite de compliquer le schéma d'entrée de ner/ dans l'éventualité où LABEL envoyait les métadonnées brutes directement.

**Comment by mauryaland** [comment]
@SebCourvoisier en entrée de meta-jurica, le texte brute de la colonne JDEC_COLL_PARTIES suffit, on parsera de notre côté. Pour meta-jurinet, comme on se l'était déjà dit par mail, un JSON représentant la requête SELECT * FROM VIEW_PARTIE WHERE ID_DOCUMENT={id du document concerné} serait top !

**Comment by SebCourvoisier** [comment]
Dans l'import des métadonnées, côté `rawJurinet` il y a désormais en plus :

* Un champ `_analyse` (array d'objets) pour les éléments d'analyse (sommaire, etc.) ;
* Un champ `_decatt` (array d'entiers) qui contient la (mais parfois les) ID de décision attaquée dans Jurica ;
* Un champ `_partie` (array d'objets) qui contient un "dump" des données issues de `SELECT * FROM VIEW_PARTIE ...`

Tout ça se retrouve dans `decisions`, dans les champs respectifs : 

* `analysis.analyse`
* `decatt`
* `parties`

**Comment by mauryaland** [comment]
Super merci, je vais mettre à jour les endpoints côté API de pseudonymisation du coup.

**Comment by SebCourvoisier** [comment]
Close issue.
